language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kurthakim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kurthakim/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-320801656457'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
